version: '2'

services:
  nginx:
    restart: always
    image: nginx:1.23 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./ssl/:/etc/nginx/ssl/:ro

  web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - "nginx"
